on: push
name: Execute test in doing push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout by the local branch
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
        env: 
          NODE_ENV: development
          PORT: 5000
          BASE_URL: http://api.openweathermap.org/data/2.5/
          API_KEY: a56b0e3cc71229c3e77d326dc2f650a8
      - name: Execute tests
        run: npm run test